### ISSUE TITLE
transition der hamburger navigation wenn responsive auf kleinen devices (zb iphone 6)

### ISSUE THREAD

**Issue by TSchertenleib** [TSchertenleib/binzenhof#4]
hey @d-simon 

no en letschts problem woni han und dänn häts sich. und zwar wänni ufem iphone 6 (und uf allne chline devices) uf s hamburger menu drucke oder uf en link wänn s menu offe isch, dänn fadets nüme schön use sondern bricht abbrubt ab.

ich han s gfühl, dass es mit mim toggleHandler ztue hät, wo irgendwie vor de transition scho ladet, und somit d transition gar nüme chan ablaufe. gits da irgend en trick? zb, dass mer seit de handler sött erst e klass lade, nachdem e bestimmti zit abglaufe isch oder so?

liebe gruess

thomas

**Comment by d-simon** [comment]
S'problem isch die ziile:
https://github.com/TSchertenleib/binzenhof/blob/master/js/main.js#L141

Anstatt dene ziile (141-142)

``` js
        $('.unterliste2').css("display", "none");
        $('.unterliste2').animate({ opacity: 0 }, 0);
```

müesstis so sii

``` js
$('.unterliste2').animate(
    {
        opacity: 0
    },
    {
        duration: 500,
        callback: function () {
              $('.unterliste2').css("display", "none");
        }
   });
```

**Comment by d-simon** [comment]
Jetzt stellt sich nur no d'frag warum duration 0 isch im original code?

**Comment by TSchertenleib** [comment]
ich glaub ich han det eifach umeprobert..

**Comment by TSchertenleib** [comment]
aber merci! das hät mer viel ghulfe!

**Comment by TSchertenleib** [comment]
cooli sach mit denä callbacks :)
